'use strict';
const $=id=>document.getElementById(id);
const han=/^\p{Script=Han}$/u;
let items=[],selected=-1,writer=null,charData=null,generation=0,operation=0,mode='idle',stroke=0;
const cache=new Map();
function report(text){$('message').textContent=text;$('main-message').textContent=text;}
async function loadData(char){const key=Math.floor(char.codePointAt(0)/128);if(!cache.has(key))cache.set(key,fetch(`data/${key}.json`).then(r=>{if(!r.ok)throw Error('missing');return r.json();}).catch(e=>{cache.delete(key);throw e;}));const data=(await cache.get(key))[char];if(!data)throw Error('missing');return data;}
function controls(ready){for(const id of ['play','step','reset'])$(id).disabled=!ready;$('play').textContent='▶ 播放笔顺';$('board').setAttribute('aria-disabled',String(!ready));}
function progress(n){stroke=n;$('progress').textContent=n?`第 ${n} / ${charData.strokes.length} 笔${n===charData.strokes.length?' · 最后一笔':''}`:'准备好了，点击播放开始';document.querySelectorAll('.stroke-card').forEach((b,i)=>b.classList.toggle('active',i===n-1));window.dispatchEvent(new CustomEvent('stroke-progress',{detail:n}));}
function stop(){operation++;if(writer){writer.pauseAnimation();writer.cancelQuiz();}mode='idle';$('play').textContent='▶ 播放笔顺';}
function createWriter(){if(writer)writer.pauseAnimation();$('writer').replaceChildren();writer=HanziWriter.create('writer',items[selected].char,{width:320,height:320,padding:25,strokeColor:'#273034',outlineColor:'#eae5e2',highlightColor:'#b6342d',showCharacter:true,showOutline:$('outline').checked,strokeAnimationSpeed:Number($('speed').value),strokeFadeDuration:0,charDataLoader:()=>charData});}
function strokeCards(){const ns='http://www.w3.org/2000/svg';$('stroke-list').replaceChildren();charData.strokes.forEach((_,index)=>{const button=document.createElement('button');button.className='stroke-card';button.type='button';button.setAttribute('aria-label',`演示第 ${index+1} 笔`);const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 100 100');svg.setAttribute('aria-hidden','true');const grid=document.createElementNS(ns,'path');grid.setAttribute('d','M50 0V100M0 50H100');grid.setAttribute('stroke','#e2dedc');grid.setAttribute('stroke-dasharray','3 3');svg.append(grid);const group=document.createElementNS(ns,'g');group.setAttribute('transform',HanziWriter.getScalingTransform(100,100,8).transform);charData.strokes.forEach((d,i)=>{const path=document.createElementNS(ns,'path');path.setAttribute('d',d);path.setAttribute('fill',i===index?'#b6342d':i<index?'#303a3f':'#efeeee');group.append(path);});svg.append(group);const label=document.createElement('span');label.textContent=index+1;button.append(svg,label);button.onclick=()=>singleStroke(index);$('stroke-list').append(button);});window.dispatchEvent(new Event('strokes-loaded'));}
async function select(index){if(!Number.isInteger(index)||!items[index]||!han.test(items[index].char))return;stop();const ticket=++generation;selected=index;charData=null;writer=null;controls(false);$('writer').replaceChildren();$('stroke-list').replaceChildren();window.dispatchEvent(new Event('strokes-loaded'));const item=items[index];$('active-pinyin').textContent=item.py;$('model-pinyin').textContent=item.py;$('model').textContent=item.char;const hanItems=items.filter(x=>han.test(x.char));$('position').textContent=`${hanItems.indexOf(item)+1} / ${hanItems.length} 字`;$('stroke-count').textContent='';$('board-message').textContent='正在加载笔顺…';$('progress').textContent='正在准备字帖…';$('stroke-note').hidden=false;document.querySelectorAll('.char').forEach(b=>{const active=Number(b.dataset.index)===index;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});window.dispatchEvent(new Event('character-selected'));try{const data=await loadData(item.char);if(ticket!==generation)return;charData=data;createWriter();strokeCards();$('board-message').textContent='';$('stroke-count').textContent=`${data.strokes.length} 画`;controls(true);progress(0);}catch(e){if(ticket!==generation)return;$('board-message').textContent=`“${item.char}”暂无笔顺数据`;$('progress').textContent='可以查看右侧楷体字样，或选择其他汉字。';$('stroke-note').hidden=true;}}
async function submit(text){if(typeof text!=='string'||[...text].length>120){report('请输入不超过 120 个字符的中文。');return false;}if(![...text].some(c=>han.test(c))){report('请输入至少一个汉字，例如：中国。');return false;}if(!window.pinyinPro||!window.HanziWriter){report('页面资源加载失败，请刷新后再试。');return false;}report('');// Keep punctuation aligned with each input character.
const pronunciation=pinyinPro.pinyin(text,{type:'array',nonZh:'spaced'});
items=[...text].map((char,i)=>({char,py:han.test(char)?pronunciation[i]||pinyinPro.pinyin(char):''}));
$('characters').replaceChildren();items.forEach((item,i)=>{if(!han.test(item.char)){const s=document.createElement('span');s.className='punctuation';s.textContent=item.char;$('characters').append(s);return;}const b=document.createElement('button');b.type='button';b.className='char';b.dataset.index=i;b.setAttribute('aria-label',`${item.char}，${item.py}，查看笔顺`);const p=document.createElement('span');p.className='py';p.textContent=item.py;const c=document.createElement('span');c.className='glyph';c.textContent=item.char;b.append(p,c);b.onclick=()=>select(i);$('characters').append(b);});$('input').blur();window.dispatchEvent(new Event('word-submitted'));await select(items.findIndex(x=>han.test(x.char)));return true;}
async function run(){if(!writer||!charData)return;if(mode==='playing'){mode='paused';writer.pauseAnimation();$('play').textContent='▶ 继续播放';return;}if(mode==='paused'){mode='playing';writer.resumeAnimation();$('play').textContent='Ⅱ 暂停';return;}stop();const id=operation;const current=writer;mode='playing';$('play').textContent='Ⅱ 暂停';$('previous-strokes')?.remove();await current.hideCharacter({duration:0});if(id!==operation)return;const count=charData.strokes.length;for(let i=0;i<count;i++){if(id!==operation)return;progress(i+1);await current.animateStroke(i);if(id!==operation)return;}mode='idle';$('progress').textContent=`${count} 笔 · 已完成`;$('play').textContent='↻ 再看一遍';}
function paintPrevious(index){$('previous-strokes')?.remove();const ns='http://www.w3.org/2000/svg';const svg=document.createElementNS(ns,'svg');svg.id='previous-strokes';svg.setAttribute('viewBox','0 0 320 320');const g=document.createElementNS(ns,'g');g.setAttribute('transform',HanziWriter.getScalingTransform(320,320,25).transform);charData.strokes.slice(0,index).forEach(d=>{const p=document.createElementNS(ns,'path');p.setAttribute('d',d);p.setAttribute('fill','#273034');g.append(p);});svg.append(g);$('writer').append(svg);}
async function singleStroke(index){if(!writer||!charData)return;stop();const id=operation;const current=writer;mode='step';await current.hideCharacter({duration:0});if(id!==operation)return;paintPrevious(index);progress(index+1);await current.animateStroke(index);if(id===operation)mode='idle';}
$('play').onclick=run;$('step').onclick=()=>singleStroke(stroke>=charData.strokes.length?0:stroke);$('reset').onclick=()=>{stop();createWriter();progress(0);};$('speed').onchange=()=>{if(charData){stop();createWriter();progress(0);}};$('outline').onchange=()=>{if(writer)writer[$('outline').checked?'showOutline':'hideOutline']({duration:0});};$('form').onsubmit=e=>{e.preventDefault();submit($('input').value);};document.querySelectorAll('[data-example]').forEach(b=>b.onclick=()=>{$('input').value=b.dataset.example;submit(b.dataset.example);});
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'show_chinese_strokes',title:'查看中文拼音与笔顺',description:'输入中文，在页面显示拼音并选择第一个汉字的笔顺。',inputSchema:{type:'object',properties:{text:{type:'string',maxLength:120}},required:['text'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},async execute(input){if(!input||typeof input.text!=='string'||![...input.text].some(c=>han.test(c))||[...input.text].length>120)throw Error('请输入 1–120 个字符且至少包含一个汉字');$('input').value=input.text;if(!await submit(input.text))throw Error('无法显示输入');return {characters:items.filter(x=>han.test(x.char)),selected:items[selected].char,strokeCount:charData?.strokes.length??null};}},{signal:lifecycle.signal})).catch(()=>{});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}catch{}}
submit($('input').value);

// Scale the SVG coordinate system with the responsive writing grid.
new MutationObserver(() => { document.querySelectorAll('#writer > svg').forEach(svg => svg.setAttribute('viewBox','0 0 320 320')); }).observe($('writer'), {childList:true});
