'use strict';
const toneNames=['第一声 · 平平的','第二声 · 往上扬','第三声 · 拐个弯','第四声 · 往下降'];
const $=id=>document.getElementById(id);
let preferences={selected:practiceGroups[0].items.map(i=>i.id),delay:10};
try{const saved=JSON.parse(localStorage.getItem('pinyin-practice-v2'));const valid=new Set(practiceItems.map(i=>i.id));if(saved&&Array.isArray(saved.selected)){const selected=[...new Set(saved.selected)].filter(id=>valid.has(id));if(selected.length&&Number.isInteger(saved.delay)&&saved.delay>=0&&saved.delay<=60)preferences={selected,delay:saved.delay};}}catch{}
let pool=makePool(preferences.selected);
let current=null,question=0,deadline=0,recorder=null,stream=null,recordUrl=null,recordTimer=null,version=0,pending=false,playing=null,playbackId=0;
function stopAudio(){playbackId++;if('speechSynthesis' in window)speechSynthesis.cancel();if(playing){playing.onended=null;playing.pause();playing=null;}}
function stopRecording(){clearTimeout(recordTimer);if(recorder?.state==='recording')recorder.stop();stream?.getTracks().forEach(t=>t.stop());stream=null;$('record').classList.remove('recording');$('record').textContent='● 录音';}
function next(){version++;stopAudio();stopRecording();if(recordUrl)URL.revokeObjectURL(recordUrl);recordUrl=null;$('replay').disabled=true;pending=false;$('record').disabled=false;const options=pool.length>1?pool.filter(item=>item.id!==current?.id):pool;current=options[Math.floor(Math.random()*options.length)];question++;deadline=Date.now()+preferences.delay*1000;$('letter').textContent=current.label;$('letter').classList.toggle('multi',current.label.length>2);$('word').textContent=current.word||'';$('word').hidden=!current.word;$('tone').textContent=current.word?'词语 · 连起来读':toneNames[current.tone];$('count').textContent=`第 ${question} 题`;$('scope').textContent=`本次已选 ${preferences.selected.length} 项 · ${pool.length} 种题目`;$('status').textContent='录音只保留在本页，换题后清除。';tick();return {pinyin:current.label,word:current.word||null,question};}
function tick(){const waiting=Date.now()<deadline;$('listen').hidden=waiting;$('waiting').hidden=!waiting;}
function say(){
  if(Date.now()<deadline)return;
  stopAudio();stopRecording();
  const token=version;
  const playback=playbackId;
  if(current.word){
    if(!('speechSynthesis' in window)){$('status').textContent='此浏览器不支持词语朗读，请使用带普通话声音的 Safari。';return;}
    const voice=speechSynthesis.getVoices().find(v=>/^(zh[-_]CN|cmn[-_]CN|zh[-_]Hans)/i.test(v.lang));
    if(!voice){$('status').textContent='未找到普通话声音。请在设备设置中下载普通话语音，再重新打开页面。';return;}
    const word=current.word;let repetition=0;
    const speak=()=>{if(token!==version||playback!==playbackId)return;repetition++;const utterance=new SpeechSynthesisUtterance(word);utterance.lang='zh-CN';utterance.voice=voice;utterance.rate=.75;utterance.onend=()=>{if(token!==version||playback!==playbackId)return;if(repetition<3)speak();else $('status').textContent='三遍听完啦，再自己读一遍吧。';};utterance.onerror=()=>{if(token===version&&playback===playbackId)$('status').textContent='词语朗读失败，请重试或检查普通话语音设置。';};$('status').textContent=`词语示范 · 第 ${repetition} 遍，共 3 遍`;speechSynthesis.speak(utterance);};speak();return;
  }
  const audio=new Audio(`audio/${current.audio}.mp3`);
  playing=audio;
  let repetition=1;
  const active=()=>token===version&&playing===audio;
  function play(){audio.play().then(()=>{if(active())$('status').textContent=`正在播放示范 · 第 ${repetition} 遍，共 3 遍`;}).catch(()=>{if(active())$('status').textContent='播放失败，请检查网络和设备音量，再点一次。';});}
  audio.onended=()=>{if(!active())return;if(repetition<3){repetition++;audio.currentTime=0;play();}else{audio.onended=null;playing=null;$('status').textContent='三遍听完啦，再自己读一遍吧。';}};
  play();
}
async function record(){if(recorder?.state==='recording'){stopRecording();return;}if(pending)return;if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){$('status').textContent='录音需要支持录音的浏览器和 HTTPS 连接，请用 Safari 打开网页。';return;}const token=version;pending=true;$('record').disabled=true;stopAudio();$('status').textContent='请允许麦克风，然后读出上面的拼音。';let acquired;try{acquired=await navigator.mediaDevices.getUserMedia({audio:true});if(token!==version){acquired.getTracks().forEach(t=>t.stop());return;}stream=acquired;const local=new MediaRecorder(stream);recorder=local;const chunks=[];local.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};local.onstop=()=>{acquired.getTracks().forEach(t=>t.stop());if(token!==version)return;if(recordUrl)URL.revokeObjectURL(recordUrl);recordUrl=URL.createObjectURL(new Blob(chunks,{type:local.mimeType}));$('replay').disabled=!chunks.length;$('status').textContent=chunks.length?'录好了！点击“回听”，再和示范比较。':'没有录到声音，请重试。';};local.onerror=()=>{stopRecording();$('status').textContent='录音中断，请重试。';};local.start();$('replay').disabled=true;$('record').textContent='■ 结束录音';$('record').classList.add('recording');$('status').textContent='正在录音…读完点击结束，最长 5 秒。';recordTimer=setTimeout(stopRecording,5000);}catch(e){acquired?.getTracks().forEach(t=>t.stop());if(token===version)$('status').textContent=e.name==='NotAllowedError'?'未获得麦克风权限，请在 Safari 网站设置中允许麦克风。':'麦克风暂时不可用，请关闭其他录音应用后重试。';}finally{if(token===version){pending=false;$('record').disabled=false;}}}
$('next').onclick=next;$('listen').onclick=say;$('record').onclick=record;$('replay').onclick=()=>{stopAudio();if(recordUrl){playing=new Audio(recordUrl);playing.play().catch(()=>{$('status').textContent='回听失败，请重新录音。';});}};
document.addEventListener('visibilitychange',()=>{if(document.hidden){version++;stopRecording();stopAudio();pending=false;$('record').disabled=false;}else tick();});window.addEventListener('pagehide',()=>{version++;stopRecording();stopAudio();if(recordUrl)URL.revokeObjectURL(recordUrl);});
for(const group of practiceGroups){const fieldset=document.createElement('fieldset');const legend=document.createElement('legend');legend.textContent=group.name;fieldset.append(legend);const controls=document.createElement('div');controls.className='group-actions';for(const [text,checked] of [['全选',true],['清空',false]]){const button=document.createElement('button');button.type='button';button.textContent=text;button.setAttribute('aria-label',`${group.name}：${text}`);button.onclick=()=>fieldset.querySelectorAll('input').forEach(input=>{input.checked=checked;});controls.append(button);}fieldset.append(controls);const choices=document.createElement('div');choices.className='choices';for(const item of group.items){const label=document.createElement('label');const input=document.createElement('input');input.type='checkbox';input.value=item.id;const span=document.createElement('span');span.textContent=item.label+(item.word?` · ${item.word}`:'');label.append(input,span);choices.append(label);}fieldset.append(choices);$('choices').append(fieldset);}
$('settings-open').onclick=()=>{version++;stopAudio();stopRecording();pending=false;$('record').disabled=false;$('delay').value=preferences.delay;$('settings-error').textContent='';$('choices').querySelectorAll('input').forEach(input=>{input.checked=preferences.selected.includes(input.value);});$('settings').showModal();};
$('settings-close').onclick=()=>$('settings').close();
$('settings-form').onsubmit=event=>{event.preventDefault();const selected=[...$('choices').querySelectorAll('input:checked')].map(input=>input.value);const delay=Number($('delay').value);if(!selected.length){$('settings-error').textContent='请至少选择一项练习内容。';return;}if($('delay').value.trim()===''||!Number.isInteger(delay)||delay<0||delay>60){$('settings-error').textContent='请输入 0–60 的整数秒数。';return;}preferences={selected,delay};pool=makePool(selected);let saved=true;try{localStorage.setItem('pinyin-practice-v2',JSON.stringify(preferences));}catch{saved=false;}question=0;current=null;$('settings').close();next();if(!saved)$('status').textContent='设置已应用；此浏览器无法保存设置，关闭页面后需重新选择。';};
if('speechSynthesis' in window)speechSynthesis.getVoices();
next();setInterval(tick,200);
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'next_pinyin',description:'从当前勾选范围中随机出题，并按照设置延迟显示示范按钮。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||Object.keys(input).length)throw new Error('不需要参数');return next();}})).catch(()=>{});}catch{}}
